/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentId = IDL.Text;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Text;
export const ResumeId = IDL.Text;
export const PaymentRecordView = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'unlockedAt' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'resumeId' : ResumeId,
  'stripePaymentIntentId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CreatePaymentInput = IDL.Record({
  'resumeId' : ResumeId,
  'stripePaymentIntentId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ProjectEntry = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
});
export const EducationEntry = IDL.Record({
  'endDate' : IDL.Text,
  'school' : IDL.Text,
  'description' : IDL.Text,
  'degree' : IDL.Text,
  'startDate' : IDL.Text,
});
export const ExperienceEntry = IDL.Record({
  'title' : IDL.Text,
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'startDate' : IDL.Text,
});
export const PersonalInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'summary' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const ResumeContent = IDL.Record({
  'projects' : IDL.Vec(ProjectEntry),
  'education' : IDL.Vec(EducationEntry),
  'experience' : IDL.Vec(ExperienceEntry),
  'personalInfo' : PersonalInfo,
  'skills' : IDL.Vec(IDL.Text),
});
export const TemplateId = IDL.Text;
export const CreateResumeInput = IDL.Record({
  'title' : IDL.Text,
  'content' : ResumeContent,
  'templateId' : TemplateId,
});
export const ResumeView = IDL.Record({
  'id' : ResumeId,
  'title' : IDL.Text,
  'content' : ResumeContent,
  'ownerId' : UserId,
  'templateId' : TemplateId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'downloadUnlocked' : IDL.Bool,
});
export const ProfileView = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'principalId' : UserId,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TemplateCategory = IDL.Variant({
  'Creative' : IDL.Null,
  'Minimal' : IDL.Null,
  'Professional' : IDL.Null,
  'Modern' : IDL.Null,
});
export const Template = IDL.Record({
  'id' : TemplateId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : TemplateCategory,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateResumeInput = IDL.Record({
  'id' : ResumeId,
  'title' : IDL.Text,
  'content' : ResumeContent,
  'templateId' : TemplateId,
});

export const idlService = IDL.Service({
  'confirmPayment' : IDL.Func([PaymentId], [PaymentRecordView], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPaymentRecord' : IDL.Func(
      [CreatePaymentInput],
      [PaymentRecordView],
      [],
    ),
  'createResume' : IDL.Func([CreateResumeInput], [ResumeView], []),
  'deleteResume' : IDL.Func([ResumeId], [IDL.Bool], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], []),
  'getMyResumes' : IDL.Func([], [IDL.Vec(ResumeView)], ['query']),
  'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecordView)], ['query']),
  'getResume' : IDL.Func([ResumeId], [IDL.Opt(ResumeView)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ProfileView],
      [],
    ),
  'updateResume' : IDL.Func([UpdateResumeInput], [ResumeView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentId = IDL.Text;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Text;
  const ResumeId = IDL.Text;
  const PaymentRecordView = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'unlockedAt' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'resumeId' : ResumeId,
    'stripePaymentIntentId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CreatePaymentInput = IDL.Record({
    'resumeId' : ResumeId,
    'stripePaymentIntentId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ProjectEntry = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
  });
  const EducationEntry = IDL.Record({
    'endDate' : IDL.Text,
    'school' : IDL.Text,
    'description' : IDL.Text,
    'degree' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const ExperienceEntry = IDL.Record({
    'title' : IDL.Text,
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const PersonalInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'summary' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const ResumeContent = IDL.Record({
    'projects' : IDL.Vec(ProjectEntry),
    'education' : IDL.Vec(EducationEntry),
    'experience' : IDL.Vec(ExperienceEntry),
    'personalInfo' : PersonalInfo,
    'skills' : IDL.Vec(IDL.Text),
  });
  const TemplateId = IDL.Text;
  const CreateResumeInput = IDL.Record({
    'title' : IDL.Text,
    'content' : ResumeContent,
    'templateId' : TemplateId,
  });
  const ResumeView = IDL.Record({
    'id' : ResumeId,
    'title' : IDL.Text,
    'content' : ResumeContent,
    'ownerId' : UserId,
    'templateId' : TemplateId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'downloadUnlocked' : IDL.Bool,
  });
  const ProfileView = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'principalId' : UserId,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TemplateCategory = IDL.Variant({
    'Creative' : IDL.Null,
    'Minimal' : IDL.Null,
    'Professional' : IDL.Null,
    'Modern' : IDL.Null,
  });
  const Template = IDL.Record({
    'id' : TemplateId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : TemplateCategory,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateResumeInput = IDL.Record({
    'id' : ResumeId,
    'title' : IDL.Text,
    'content' : ResumeContent,
    'templateId' : TemplateId,
  });
  
  return IDL.Service({
    'confirmPayment' : IDL.Func([PaymentId], [PaymentRecordView], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPaymentRecord' : IDL.Func(
        [CreatePaymentInput],
        [PaymentRecordView],
        [],
      ),
    'createResume' : IDL.Func([CreateResumeInput], [ResumeView], []),
    'deleteResume' : IDL.Func([ResumeId], [IDL.Bool], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(ProfileView)], []),
    'getMyResumes' : IDL.Func([], [IDL.Vec(ResumeView)], ['query']),
    'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecordView)], ['query']),
    'getResume' : IDL.Func([ResumeId], [IDL.Opt(ResumeView)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTemplate' : IDL.Func([TemplateId], [IDL.Opt(Template)], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ProfileView],
        [],
      ),
    'updateResume' : IDL.Func([UpdateResumeInput], [ResumeView], []),
  });
};

export const init = ({ IDL }) => { return []; };