/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreatePaymentInput {
  'resumeId' : ResumeId,
  'stripePaymentIntentId' : string,
  'amount' : bigint,
}
export interface CreateResumeInput {
  'title' : string,
  'content' : ResumeContent,
  'templateId' : TemplateId,
}
export interface EducationEntry {
  'endDate' : string,
  'school' : string,
  'description' : string,
  'degree' : string,
  'startDate' : string,
}
export interface ExperienceEntry {
  'title' : string,
  'endDate' : string,
  'description' : string,
  'company' : string,
  'startDate' : string,
}
export type PaymentId = string;
export interface PaymentRecordView {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'unlockedAt' : [] | [Timestamp],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'resumeId' : ResumeId,
  'stripePaymentIntentId' : string,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export interface PersonalInfo {
  'name' : string,
  'email' : string,
  'summary' : string,
  'phone' : string,
  'location' : string,
}
export interface ProfileView {
  'name' : [] | [string],
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'principalId' : UserId,
}
export interface ProjectEntry {
  'title' : string,
  'link' : string,
  'description' : string,
}
export interface ResumeContent {
  'projects' : Array<ProjectEntry>,
  'education' : Array<EducationEntry>,
  'experience' : Array<ExperienceEntry>,
  'personalInfo' : PersonalInfo,
  'skills' : Array<string>,
}
export type ResumeId = string;
export interface ResumeView {
  'id' : ResumeId,
  'title' : string,
  'content' : ResumeContent,
  'ownerId' : UserId,
  'templateId' : TemplateId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'downloadUnlocked' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Template {
  'id' : TemplateId,
  'name' : string,
  'description' : string,
  'category' : TemplateCategory,
}
export type TemplateCategory = { 'Creative' : null } |
  { 'Minimal' : null } |
  { 'Academic' : null } |
  { 'Executive' : null } |
  { 'Professional' : null } |
  { 'StartupTech' : null } |
  { 'TwoColumn' : null } |
  { 'Modern' : null };
export type TemplateId = string;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateResumeInput {
  'id' : ResumeId,
  'title' : string,
  'content' : ResumeContent,
  'templateId' : TemplateId,
}
export type UserId = string;
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'confirmPayment' : ActorMethod<[PaymentId], PaymentRecordView>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPaymentRecord' : ActorMethod<[CreatePaymentInput], PaymentRecordView>,
  'createResume' : ActorMethod<[CreateResumeInput], ResumeView>,
  'deleteResume' : ActorMethod<[ResumeId], boolean>,
  'getMyProfile' : ActorMethod<[], [] | [ProfileView]>,
  'getMyResumes' : ActorMethod<[], Array<ResumeView>>,
  'getPaymentHistory' : ActorMethod<[], Array<PaymentRecordView>>,
  'getResume' : ActorMethod<[ResumeId], [] | [ResumeView]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTemplate' : ActorMethod<[TemplateId], [] | [Template]>,
  'getTemplates' : ActorMethod<[], Array<Template>>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMyProfile' : ActorMethod<[[] | [string], [] | [string]], ProfileView>,
  'updateResume' : ActorMethod<[UpdateResumeInput], ResumeView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];