/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CreatePaymentInput {
    resumeId: ResumeId;
    stripePaymentIntentId: string;
    amount: bigint;
}
export interface CreateResumeInput {
    title: string;
    content: ResumeContent;
    templateId: TemplateId;
}
export type TemplateId = string;
export interface PersonalInfo {
    name: string;
    email: string;
    summary: string;
    phone: string;
    location: string;
}
export interface ExperienceEntry {
    title: string;
    endDate: string;
    description: string;
    company: string;
    startDate: string;
}
export interface EducationEntry {
    endDate: string;
    school: string;
    description: string;
    degree: string;
    startDate: string;
}
export interface Template {
    id: TemplateId;
    name: string;
    description: string;
    category: TemplateCategory;
}
export interface http_header {
    value: string;
    name: string;
}
export interface ResumeView {
    id: ResumeId;
    title: string;
    content: ResumeContent;
    ownerId: UserId;
    templateId: TemplateId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    downloadUnlocked: boolean;
}
export type UserId = string;
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type ResumeId = string;
export interface ProfileView {
    name?: string;
    createdAt: Timestamp;
    email?: string;
    principalId: UserId;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UpdateResumeInput {
    id: ResumeId;
    title: string;
    content: ResumeContent;
    templateId: TemplateId;
}
export interface PaymentRecordView {
    id: PaymentId;
    status: PaymentStatus;
    unlockedAt?: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    resumeId: ResumeId;
    stripePaymentIntentId: string;
    amount: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface ResumeContent {
    projects: Array<ProjectEntry>;
    education: Array<EducationEntry>;
    experience: Array<ExperienceEntry>;
    personalInfo: PersonalInfo;
    skills: Array<string>;
}
export interface ProjectEntry {
    title: string;
    link: string;
    description: string;
}
export type PaymentId = string;
export enum PaymentStatus {
    pending = "pending",
    success = "success",
    failed = "failed"
}
export enum TemplateCategory {
    Creative = "Creative",
    Minimal = "Minimal",
    Academic = "Academic",
    Executive = "Executive",
    Professional = "Professional",
    StartupTech = "StartupTech",
    TwoColumn = "TwoColumn",
    Modern = "Modern"
}
export interface backendInterface {
    confirmPayment(paymentId: PaymentId): Promise<PaymentRecordView>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPaymentRecord(input: CreatePaymentInput): Promise<PaymentRecordView>;
    createResume(input: CreateResumeInput): Promise<ResumeView>;
    deleteResume(resumeId: ResumeId): Promise<boolean>;
    getMyProfile(): Promise<ProfileView | null>;
    getMyResumes(): Promise<Array<ResumeView>>;
    getPaymentHistory(): Promise<Array<PaymentRecordView>>;
    getResume(resumeId: ResumeId): Promise<ResumeView | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTemplate(templateId: TemplateId): Promise<Template | null>;
    getTemplates(): Promise<Array<Template>>;
    isStripeConfigured(): Promise<boolean>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateMyProfile(email: string | null, name: string | null): Promise<ProfileView>;
    updateResume(input: UpdateResumeInput): Promise<ResumeView>;
}
import type { PaymentId as _PaymentId, PaymentRecordView as _PaymentRecordView, PaymentStatus as _PaymentStatus, ProfileView as _ProfileView, ResumeId as _ResumeId, ResumeView as _ResumeView, StripeSessionStatus as _StripeSessionStatus, Template as _Template, TemplateCategory as _TemplateCategory, TemplateId as _TemplateId, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async confirmPayment(arg0: PaymentId): Promise<PaymentRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return from_candid_PaymentRecordView_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return from_candid_PaymentRecordView_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPaymentRecord(arg0: CreatePaymentInput): Promise<PaymentRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentRecord(arg0);
                return from_candid_PaymentRecordView_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentRecord(arg0);
            return from_candid_PaymentRecordView_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createResume(arg0: CreateResumeInput): Promise<ResumeView> {
        if (this.processError) {
            try {
                const result = await this.actor.createResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResume(arg0);
            return result;
        }
    }
    async deleteResume(arg0: ResumeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<ProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyResumes(): Promise<Array<ResumeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyResumes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyResumes();
            return result;
        }
    }
    async getPaymentHistory(): Promise<Array<PaymentRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentHistory();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentHistory();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResume(arg0: ResumeId): Promise<ResumeView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplate(arg0: TemplateId): Promise<Template | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplate(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplate(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplates(): Promise<Array<Template>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplates();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplates();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateMyProfile(arg0: string | null, arg1: string | null): Promise<ProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ProfileView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ProfileView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResume(arg0: UpdateResumeInput): Promise<ResumeView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResume(arg0);
            return result;
        }
    }
}
function from_candid_PaymentRecordView_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecordView): PaymentRecordView {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileView): ProfileView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TemplateCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TemplateCategory): TemplateCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Template_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Template): Template {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResumeView]): ResumeView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Template]): Template | null {
    return value.length === 0 ? null : from_candid_Template_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileView]): ProfileView | null {
    return value.length === 0 ? null : from_candid_ProfileView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TemplateId;
    name: string;
    description: string;
    category: _TemplateCategory;
}): {
    id: TemplateId;
    name: string;
    description: string;
    category: TemplateCategory;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: from_candid_TemplateCategory_n18(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    status: _PaymentStatus;
    unlockedAt: [] | [_Timestamp];
    userId: _UserId;
    createdAt: _Timestamp;
    resumeId: _ResumeId;
    stripePaymentIntentId: string;
    amount: bigint;
}): {
    id: PaymentId;
    status: PaymentStatus;
    unlockedAt?: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    resumeId: ResumeId;
    stripePaymentIntentId: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n3(_uploadFile, _downloadFile, value.status),
        unlockedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.unlockedAt)),
        userId: value.userId,
        createdAt: value.createdAt,
        resumeId: value.resumeId,
        stripePaymentIntentId: value.stripePaymentIntentId,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: [] | [string];
    createdAt: _Timestamp;
    email: [] | [string];
    principalId: _UserId;
}): {
    name?: string;
    createdAt: Timestamp;
    email?: string;
    principalId: UserId;
} {
    return {
        name: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.name)),
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.email)),
        principalId: value.principalId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n14(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Creative: null;
} | {
    Minimal: null;
} | {
    Academic: null;
} | {
    Executive: null;
} | {
    Professional: null;
} | {
    StartupTech: null;
} | {
    TwoColumn: null;
} | {
    Modern: null;
}): TemplateCategory {
    return "Creative" in value ? TemplateCategory.Creative : "Minimal" in value ? TemplateCategory.Minimal : "Academic" in value ? TemplateCategory.Academic : "Executive" in value ? TemplateCategory.Executive : "Professional" in value ? TemplateCategory.Professional : "StartupTech" in value ? TemplateCategory.StartupTech : "TwoColumn" in value ? TemplateCategory.TwoColumn : "Modern" in value ? TemplateCategory.Modern : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    success: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "success" in value ? PaymentStatus.success : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecordView>): Array<PaymentRecordView> {
    return value.map((x)=>from_candid_PaymentRecordView_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Template>): Array<Template> {
    return value.map((x)=>from_candid_Template_n16(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
